kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: alpine
  commands:
    - echo "Hello World"
- name: build2
  pull: always
  image: alpine
  commands:
    - echo "Hello World"
